[package]
name = "hyperlane-log"
version = "1.1.4"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """A Rust asynchronous logging library that runs on a dedicated thread to avoid blocking other threads. It supports multiple log levels (such as error, info, and debug), and allows custom log handling methods and configuration of log file paths. When a single log file reaches the specified size limit, a new log file will be automatically created."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/ltpp-universe/hyperlane-log.git"
categories = ["network-programming", "web-programming","development-tools"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
file-operation = "0.3.0"
http-type = "2.30.1"
hyperlane-time = "0.0.3"
lombok-macros = "1.7.0"
once_cell = "1.20.2"
recoverable-spawn = "3.3.1"
